name: Security

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install safety bandit

      - name: Check for security vulnerabilities with safety
        run: |
          pip install -r requirements.txt
          safety check --json || true

      - name: Run security linter with bandit
        run: |
          bandit -r . -f json -o bandit-report.json || true
          bandit -r . || true
